logging:
  level:
    root: info

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    url: jdbc:postgresql://localhost:5432/airline_tickets_system
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

jwt:
  secret-key: 6A576E5A7234753778214125442A472D4B614E645267556B58703273357638792F423F4528482B4D6251655368566D597133743677397A24432646294A404E63
  expiration-time: 864000000

open-weather-map:
  use-mock: true
  x-rapidapi-key: 5203b77f0emsha535f088ddf7d79p1f4773jsn935a1e67f4fb
  x-rapidapi-host: community-open-weather-map.p.rapidapi.com
  search-weather-data-url: https://community-open-weather-map.p.rapidapi.com/find?q=%s&units=metric

job:
  clear-weather-cache:
    cron-expresion: 0 0 */8 ? * *     # every 8 h


