logging:
  level:
    root: info

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: postgres://obgbuqgvnhphnd:539bb05b6b483c8b3a4d4eb7286f64df2ed33b447c8247c7ef8317640944c098@ec2-176-34-105-15.eu-west-1.compute.amazonaws.com:5432/d8d3be3ggg72ie
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
  #Email configurations
  mail:
    host: smtp.gmail.com
    username: app.under.development@gmail.com
    password: ${APP_EMAIL_PASSWORD:ztqrbpokkijbgywb}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #RabbitMQ config
  rabbitmq:
    host: stingray.rmq.cloudamqp.com
    virtual-host: ajmyskak
    port: 5672
    username: ajmyskak
    password: tuKjWGB9JrrHyoYHAs_2m9p2wkuSrpdk

jwt:
  secret-key: 6A576E5A7234753778214125442A472D4B614E645267556B58703273357638792F423F4528482B4D6251655368566D597133743677397A24432646294A404E63
  expiration-time: 864000000

open-weather-map:
  use-mock: true
  x-rapidapi-key: 5203b77f0emsha535f088ddf7d79p1f4773jsn935a1e67f4fb
  x-rapidapi-host: community-open-weather-map.p.rapidapi.com
  search-weather-data-url: https://community-open-weather-map.p.rapidapi.com/find?q=%s&units=metric

job:
  clear-weather-cache:
    cron-expresion: 0 0 */8 ? * *     # every 8 h

# Exchange + Queue config
event:
  notification-exchange: notification.exchange
  email-queue: email.queue
  notification-email-routing-key: notification.email.routingkey
